trigger:
  branches:
    include:
      - feature/*
# Uncomment the above lines if you want to trigger the pipeline only for the 'jamee' branch

pool:
  vmImage: 'ubuntu-latest'  

steps:
  - checkout: self
    fetchDepth: 0  

# Prepare Analysis Configuration task
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'dmcr-sonarqube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '$(projectKey)'      

# Run Code Analysis task
  - task: SonarQubeAnalyze@5
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

# Publish Quality Gate Result task
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
      
